// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v7.34.1
// source: colima_ui.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ColimaService_Start_FullMethodName           = "/colimaui.ColimaService/Start"
	ColimaService_Stop_FullMethodName            = "/colimaui.ColimaService/Stop"
	ColimaService_Restart_FullMethodName         = "/colimaui.ColimaService/Restart"
	ColimaService_Delete_FullMethodName          = "/colimaui.ColimaService/Delete"
	ColimaService_Status_FullMethodName          = "/colimaui.ColimaService/Status"
	ColimaService_Version_FullMethodName         = "/colimaui.ColimaService/Version"
	ColimaService_Update_FullMethodName          = "/colimaui.ColimaService/Update"
	ColimaService_Prune_FullMethodName           = "/colimaui.ColimaService/Prune"
	ColimaService_SSHConfig_FullMethodName       = "/colimaui.ColimaService/SSHConfig"
	ColimaService_ListProfiles_FullMethodName    = "/colimaui.ColimaService/ListProfiles"
	ColimaService_ListMachines_FullMethodName    = "/colimaui.ColimaService/ListMachines"
	ColimaService_CreateProfile_FullMethodName   = "/colimaui.ColimaService/CreateProfile"
	ColimaService_DeleteProfile_FullMethodName   = "/colimaui.ColimaService/DeleteProfile"
	ColimaService_CloneProfile_FullMethodName    = "/colimaui.ColimaService/CloneProfile"
	ColimaService_GetConfig_FullMethodName       = "/colimaui.ColimaService/GetConfig"
	ColimaService_SetConfig_FullMethodName       = "/colimaui.ColimaService/SetConfig"
	ColimaService_GetTemplate_FullMethodName     = "/colimaui.ColimaService/GetTemplate"
	ColimaService_SetTemplate_FullMethodName     = "/colimaui.ColimaService/SetTemplate"
	ColimaService_KubernetesStart_FullMethodName = "/colimaui.ColimaService/KubernetesStart"
	ColimaService_KubernetesStop_FullMethodName  = "/colimaui.ColimaService/KubernetesStop"
	ColimaService_KubernetesReset_FullMethodName = "/colimaui.ColimaService/KubernetesReset"
	ColimaService_KubernetesExec_FullMethodName  = "/colimaui.ColimaService/KubernetesExec"
	ColimaService_ModelSetup_FullMethodName      = "/colimaui.ColimaService/ModelSetup"
	ColimaService_ModelRun_FullMethodName        = "/colimaui.ColimaService/ModelRun"
	ColimaService_ModelServe_FullMethodName      = "/colimaui.ColimaService/ModelServe"
	ColimaService_ModelStop_FullMethodName       = "/colimaui.ColimaService/ModelStop"
	ColimaService_SwitchRuntime_FullMethodName   = "/colimaui.ColimaService/SwitchRuntime"
	ColimaService_UpdateRuntime_FullMethodName   = "/colimaui.ColimaService/UpdateRuntime"
	ColimaService_VMStats_FullMethodName         = "/colimaui.ColimaService/VMStats"
	ColimaService_ProcessList_FullMethodName     = "/colimaui.ColimaService/ProcessList"
	ColimaService_KillProcess_FullMethodName     = "/colimaui.ColimaService/KillProcess"
)

// ColimaServiceClient is the client API for ColimaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ColimaService wraps the Colima CLI operations via gRPC.
type ColimaServiceClient interface {
	// VM Lifecycle
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (ColimaService_StartClient, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (ColimaService_RestartClient, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*VMStatus, error)
	Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	Update(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// SSH
	SSHConfig(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*SSHConfigResponse, error)
	// Profiles
	ListProfiles(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProfileList, error)
	ListMachines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MachineList, error)
	CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	CloneProfile(ctx context.Context, in *CloneProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Configuration
	GetConfig(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ColimaConfig, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetTemplate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ColimaConfig, error)
	SetTemplate(ctx context.Context, in *ColimaConfig, opts ...grpc.CallOption) (*StatusResponse, error)
	// Kubernetes
	KubernetesStart(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	KubernetesStop(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	KubernetesReset(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	KubernetesExec(ctx context.Context, in *KubeExecRequest, opts ...grpc.CallOption) (*KubeExecResponse, error)
	// AI Models
	ModelSetup(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (ColimaService_ModelSetupClient, error)
	ModelRun(ctx context.Context, in *ModelRunRequest, opts ...grpc.CallOption) (ColimaService_ModelRunClient, error)
	ModelServe(ctx context.Context, in *ModelServeRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ModelStop(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Runtime
	SwitchRuntime(ctx context.Context, in *SwitchRuntimeRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	UpdateRuntime(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Monitoring (streaming)
	VMStats(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (ColimaService_VMStatsClient, error)
	ProcessList(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProcessListResponse, error)
	KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type colimaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewColimaServiceClient(cc grpc.ClientConnInterface) ColimaServiceClient {
	return &colimaServiceClient{cc}
}

func (c *colimaServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (ColimaService_StartClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ColimaService_ServiceDesc.Streams[0], ColimaService_Start_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &colimaServiceStartClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ColimaService_StartClient interface {
	Recv() (*ProgressEvent, error)
	grpc.ClientStream
}

type colimaServiceStartClient struct {
	grpc.ClientStream
}

func (x *colimaServiceStartClient) Recv() (*ProgressEvent, error) {
	m := new(ProgressEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *colimaServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (ColimaService_RestartClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ColimaService_ServiceDesc.Streams[1], ColimaService_Restart_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &colimaServiceRestartClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ColimaService_RestartClient interface {
	Recv() (*ProgressEvent, error)
	grpc.ClientStream
}

type colimaServiceRestartClient struct {
	grpc.ClientStream
}

func (x *colimaServiceRestartClient) Recv() (*ProgressEvent, error) {
	m := new(ProgressEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *colimaServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*VMStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMStatus)
	err := c.cc.Invoke(ctx, ColimaService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, ColimaService_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) Update(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_Prune_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) SSHConfig(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*SSHConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSHConfigResponse)
	err := c.cc.Invoke(ctx, ColimaService_SSHConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) ListProfiles(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProfileList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileList)
	err := c.cc.Invoke(ctx, ColimaService_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) ListMachines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MachineList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineList)
	err := c.cc.Invoke(ctx, ColimaService_ListMachines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_CreateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_DeleteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) CloneProfile(ctx context.Context, in *CloneProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_CloneProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) GetConfig(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ColimaConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ColimaConfig)
	err := c.cc.Invoke(ctx, ColimaService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) GetTemplate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ColimaConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ColimaConfig)
	err := c.cc.Invoke(ctx, ColimaService_GetTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) SetTemplate(ctx context.Context, in *ColimaConfig, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_SetTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) KubernetesStart(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_KubernetesStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) KubernetesStop(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_KubernetesStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) KubernetesReset(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_KubernetesReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) KubernetesExec(ctx context.Context, in *KubeExecRequest, opts ...grpc.CallOption) (*KubeExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KubeExecResponse)
	err := c.cc.Invoke(ctx, ColimaService_KubernetesExec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) ModelSetup(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (ColimaService_ModelSetupClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ColimaService_ServiceDesc.Streams[2], ColimaService_ModelSetup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &colimaServiceModelSetupClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ColimaService_ModelSetupClient interface {
	Recv() (*ProgressEvent, error)
	grpc.ClientStream
}

type colimaServiceModelSetupClient struct {
	grpc.ClientStream
}

func (x *colimaServiceModelSetupClient) Recv() (*ProgressEvent, error) {
	m := new(ProgressEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *colimaServiceClient) ModelRun(ctx context.Context, in *ModelRunRequest, opts ...grpc.CallOption) (ColimaService_ModelRunClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ColimaService_ServiceDesc.Streams[3], ColimaService_ModelRun_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &colimaServiceModelRunClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ColimaService_ModelRunClient interface {
	Recv() (*ProgressEvent, error)
	grpc.ClientStream
}

type colimaServiceModelRunClient struct {
	grpc.ClientStream
}

func (x *colimaServiceModelRunClient) Recv() (*ProgressEvent, error) {
	m := new(ProgressEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *colimaServiceClient) ModelServe(ctx context.Context, in *ModelServeRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_ModelServe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) ModelStop(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_ModelStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) SwitchRuntime(ctx context.Context, in *SwitchRuntimeRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_SwitchRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) UpdateRuntime(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_UpdateRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) VMStats(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (ColimaService_VMStatsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ColimaService_ServiceDesc.Streams[4], ColimaService_VMStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &colimaServiceVMStatsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ColimaService_VMStatsClient interface {
	Recv() (*VMStatsEvent, error)
	grpc.ClientStream
}

type colimaServiceVMStatsClient struct {
	grpc.ClientStream
}

func (x *colimaServiceVMStatsClient) Recv() (*VMStatsEvent, error) {
	m := new(VMStatsEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *colimaServiceClient) ProcessList(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProcessListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessListResponse)
	err := c.cc.Invoke(ctx, ColimaService_ProcessList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *colimaServiceClient) KillProcess(ctx context.Context, in *KillProcessRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ColimaService_KillProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ColimaServiceServer is the server API for ColimaService service.
// All implementations must embed UnimplementedColimaServiceServer
// for forward compatibility
//
// ColimaService wraps the Colima CLI operations via gRPC.
type ColimaServiceServer interface {
	// VM Lifecycle
	Start(*StartRequest, ColimaService_StartServer) error
	Stop(context.Context, *StopRequest) (*StatusResponse, error)
	Restart(*RestartRequest, ColimaService_RestartServer) error
	Delete(context.Context, *DeleteRequest) (*StatusResponse, error)
	Status(context.Context, *StatusRequest) (*VMStatus, error)
	Version(context.Context, *Empty) (*VersionResponse, error)
	Update(context.Context, *Empty) (*StatusResponse, error)
	Prune(context.Context, *PruneRequest) (*StatusResponse, error)
	// SSH
	SSHConfig(context.Context, *ProfileRequest) (*SSHConfigResponse, error)
	// Profiles
	ListProfiles(context.Context, *Empty) (*ProfileList, error)
	ListMachines(context.Context, *Empty) (*MachineList, error)
	CreateProfile(context.Context, *CreateProfileRequest) (*StatusResponse, error)
	DeleteProfile(context.Context, *DeleteProfileRequest) (*StatusResponse, error)
	CloneProfile(context.Context, *CloneProfileRequest) (*StatusResponse, error)
	// Configuration
	GetConfig(context.Context, *ProfileRequest) (*ColimaConfig, error)
	SetConfig(context.Context, *SetConfigRequest) (*StatusResponse, error)
	GetTemplate(context.Context, *Empty) (*ColimaConfig, error)
	SetTemplate(context.Context, *ColimaConfig) (*StatusResponse, error)
	// Kubernetes
	KubernetesStart(context.Context, *ProfileRequest) (*StatusResponse, error)
	KubernetesStop(context.Context, *ProfileRequest) (*StatusResponse, error)
	KubernetesReset(context.Context, *ProfileRequest) (*StatusResponse, error)
	KubernetesExec(context.Context, *KubeExecRequest) (*KubeExecResponse, error)
	// AI Models
	ModelSetup(*ModelRequest, ColimaService_ModelSetupServer) error
	ModelRun(*ModelRunRequest, ColimaService_ModelRunServer) error
	ModelServe(context.Context, *ModelServeRequest) (*StatusResponse, error)
	ModelStop(context.Context, *ProfileRequest) (*StatusResponse, error)
	// Runtime
	SwitchRuntime(context.Context, *SwitchRuntimeRequest) (*StatusResponse, error)
	UpdateRuntime(context.Context, *ProfileRequest) (*StatusResponse, error)
	// Monitoring (streaming)
	VMStats(*ProfileRequest, ColimaService_VMStatsServer) error
	ProcessList(context.Context, *ProfileRequest) (*ProcessListResponse, error)
	KillProcess(context.Context, *KillProcessRequest) (*StatusResponse, error)
	mustEmbedUnimplementedColimaServiceServer()
}

// UnimplementedColimaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedColimaServiceServer struct {
}

func (UnimplementedColimaServiceServer) Start(*StartRequest, ColimaService_StartServer) error {
	return status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedColimaServiceServer) Stop(context.Context, *StopRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedColimaServiceServer) Restart(*RestartRequest, ColimaService_RestartServer) error {
	return status.Errorf(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedColimaServiceServer) Delete(context.Context, *DeleteRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedColimaServiceServer) Status(context.Context, *StatusRequest) (*VMStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedColimaServiceServer) Version(context.Context, *Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedColimaServiceServer) Update(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedColimaServiceServer) Prune(context.Context, *PruneRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prune not implemented")
}
func (UnimplementedColimaServiceServer) SSHConfig(context.Context, *ProfileRequest) (*SSHConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSHConfig not implemented")
}
func (UnimplementedColimaServiceServer) ListProfiles(context.Context, *Empty) (*ProfileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedColimaServiceServer) ListMachines(context.Context, *Empty) (*MachineList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMachines not implemented")
}
func (UnimplementedColimaServiceServer) CreateProfile(context.Context, *CreateProfileRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProfile not implemented")
}
func (UnimplementedColimaServiceServer) DeleteProfile(context.Context, *DeleteProfileRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (UnimplementedColimaServiceServer) CloneProfile(context.Context, *CloneProfileRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloneProfile not implemented")
}
func (UnimplementedColimaServiceServer) GetConfig(context.Context, *ProfileRequest) (*ColimaConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedColimaServiceServer) SetConfig(context.Context, *SetConfigRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedColimaServiceServer) GetTemplate(context.Context, *Empty) (*ColimaConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplate not implemented")
}
func (UnimplementedColimaServiceServer) SetTemplate(context.Context, *ColimaConfig) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTemplate not implemented")
}
func (UnimplementedColimaServiceServer) KubernetesStart(context.Context, *ProfileRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KubernetesStart not implemented")
}
func (UnimplementedColimaServiceServer) KubernetesStop(context.Context, *ProfileRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KubernetesStop not implemented")
}
func (UnimplementedColimaServiceServer) KubernetesReset(context.Context, *ProfileRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KubernetesReset not implemented")
}
func (UnimplementedColimaServiceServer) KubernetesExec(context.Context, *KubeExecRequest) (*KubeExecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KubernetesExec not implemented")
}
func (UnimplementedColimaServiceServer) ModelSetup(*ModelRequest, ColimaService_ModelSetupServer) error {
	return status.Errorf(codes.Unimplemented, "method ModelSetup not implemented")
}
func (UnimplementedColimaServiceServer) ModelRun(*ModelRunRequest, ColimaService_ModelRunServer) error {
	return status.Errorf(codes.Unimplemented, "method ModelRun not implemented")
}
func (UnimplementedColimaServiceServer) ModelServe(context.Context, *ModelServeRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModelServe not implemented")
}
func (UnimplementedColimaServiceServer) ModelStop(context.Context, *ProfileRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModelStop not implemented")
}
func (UnimplementedColimaServiceServer) SwitchRuntime(context.Context, *SwitchRuntimeRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwitchRuntime not implemented")
}
func (UnimplementedColimaServiceServer) UpdateRuntime(context.Context, *ProfileRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRuntime not implemented")
}
func (UnimplementedColimaServiceServer) VMStats(*ProfileRequest, ColimaService_VMStatsServer) error {
	return status.Errorf(codes.Unimplemented, "method VMStats not implemented")
}
func (UnimplementedColimaServiceServer) ProcessList(context.Context, *ProfileRequest) (*ProcessListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessList not implemented")
}
func (UnimplementedColimaServiceServer) KillProcess(context.Context, *KillProcessRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillProcess not implemented")
}
func (UnimplementedColimaServiceServer) mustEmbedUnimplementedColimaServiceServer() {}

// UnsafeColimaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ColimaServiceServer will
// result in compilation errors.
type UnsafeColimaServiceServer interface {
	mustEmbedUnimplementedColimaServiceServer()
}

func RegisterColimaServiceServer(s grpc.ServiceRegistrar, srv ColimaServiceServer) {
	s.RegisterService(&ColimaService_ServiceDesc, srv)
}

func _ColimaService_Start_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ColimaServiceServer).Start(m, &colimaServiceStartServer{ServerStream: stream})
}

type ColimaService_StartServer interface {
	Send(*ProgressEvent) error
	grpc.ServerStream
}

type colimaServiceStartServer struct {
	grpc.ServerStream
}

func (x *colimaServiceStartServer) Send(m *ProgressEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _ColimaService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_Restart_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RestartRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ColimaServiceServer).Restart(m, &colimaServiceRestartServer{ServerStream: stream})
}

type ColimaService_RestartServer interface {
	Send(*ProgressEvent) error
	grpc.ServerStream
}

type colimaServiceRestartServer struct {
	grpc.ServerStream
}

func (x *colimaServiceRestartServer) Send(m *ProgressEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _ColimaService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).Version(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).Update(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_Prune_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).Prune(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_Prune_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).Prune(ctx, req.(*PruneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_SSHConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).SSHConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_SSHConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).SSHConfig(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).ListProfiles(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_ListMachines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).ListMachines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_ListMachines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).ListMachines(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_CreateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).CreateProfile(ctx, req.(*CreateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_DeleteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).DeleteProfile(ctx, req.(*DeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_CloneProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).CloneProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_CloneProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).CloneProfile(ctx, req.(*CloneProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).GetConfig(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_GetTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).GetTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_GetTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).GetTemplate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_SetTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColimaConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).SetTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_SetTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).SetTemplate(ctx, req.(*ColimaConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_KubernetesStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).KubernetesStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_KubernetesStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).KubernetesStart(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_KubernetesStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).KubernetesStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_KubernetesStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).KubernetesStop(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_KubernetesReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).KubernetesReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_KubernetesReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).KubernetesReset(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_KubernetesExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KubeExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).KubernetesExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_KubernetesExec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).KubernetesExec(ctx, req.(*KubeExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_ModelSetup_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ModelRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ColimaServiceServer).ModelSetup(m, &colimaServiceModelSetupServer{ServerStream: stream})
}

type ColimaService_ModelSetupServer interface {
	Send(*ProgressEvent) error
	grpc.ServerStream
}

type colimaServiceModelSetupServer struct {
	grpc.ServerStream
}

func (x *colimaServiceModelSetupServer) Send(m *ProgressEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _ColimaService_ModelRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ModelRunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ColimaServiceServer).ModelRun(m, &colimaServiceModelRunServer{ServerStream: stream})
}

type ColimaService_ModelRunServer interface {
	Send(*ProgressEvent) error
	grpc.ServerStream
}

type colimaServiceModelRunServer struct {
	grpc.ServerStream
}

func (x *colimaServiceModelRunServer) Send(m *ProgressEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _ColimaService_ModelServe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelServeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).ModelServe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_ModelServe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).ModelServe(ctx, req.(*ModelServeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_ModelStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).ModelStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_ModelStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).ModelStop(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_SwitchRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).SwitchRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_SwitchRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).SwitchRuntime(ctx, req.(*SwitchRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_UpdateRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).UpdateRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_UpdateRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).UpdateRuntime(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_VMStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProfileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ColimaServiceServer).VMStats(m, &colimaServiceVMStatsServer{ServerStream: stream})
}

type ColimaService_VMStatsServer interface {
	Send(*VMStatsEvent) error
	grpc.ServerStream
}

type colimaServiceVMStatsServer struct {
	grpc.ServerStream
}

func (x *colimaServiceVMStatsServer) Send(m *VMStatsEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _ColimaService_ProcessList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).ProcessList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_ProcessList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).ProcessList(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ColimaService_KillProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ColimaServiceServer).KillProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ColimaService_KillProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ColimaServiceServer).KillProcess(ctx, req.(*KillProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ColimaService_ServiceDesc is the grpc.ServiceDesc for ColimaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ColimaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "colimaui.ColimaService",
	HandlerType: (*ColimaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stop",
			Handler:    _ColimaService_Stop_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ColimaService_Delete_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _ColimaService_Status_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _ColimaService_Version_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ColimaService_Update_Handler,
		},
		{
			MethodName: "Prune",
			Handler:    _ColimaService_Prune_Handler,
		},
		{
			MethodName: "SSHConfig",
			Handler:    _ColimaService_SSHConfig_Handler,
		},
		{
			MethodName: "ListProfiles",
			Handler:    _ColimaService_ListProfiles_Handler,
		},
		{
			MethodName: "ListMachines",
			Handler:    _ColimaService_ListMachines_Handler,
		},
		{
			MethodName: "CreateProfile",
			Handler:    _ColimaService_CreateProfile_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _ColimaService_DeleteProfile_Handler,
		},
		{
			MethodName: "CloneProfile",
			Handler:    _ColimaService_CloneProfile_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _ColimaService_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _ColimaService_SetConfig_Handler,
		},
		{
			MethodName: "GetTemplate",
			Handler:    _ColimaService_GetTemplate_Handler,
		},
		{
			MethodName: "SetTemplate",
			Handler:    _ColimaService_SetTemplate_Handler,
		},
		{
			MethodName: "KubernetesStart",
			Handler:    _ColimaService_KubernetesStart_Handler,
		},
		{
			MethodName: "KubernetesStop",
			Handler:    _ColimaService_KubernetesStop_Handler,
		},
		{
			MethodName: "KubernetesReset",
			Handler:    _ColimaService_KubernetesReset_Handler,
		},
		{
			MethodName: "KubernetesExec",
			Handler:    _ColimaService_KubernetesExec_Handler,
		},
		{
			MethodName: "ModelServe",
			Handler:    _ColimaService_ModelServe_Handler,
		},
		{
			MethodName: "ModelStop",
			Handler:    _ColimaService_ModelStop_Handler,
		},
		{
			MethodName: "SwitchRuntime",
			Handler:    _ColimaService_SwitchRuntime_Handler,
		},
		{
			MethodName: "UpdateRuntime",
			Handler:    _ColimaService_UpdateRuntime_Handler,
		},
		{
			MethodName: "ProcessList",
			Handler:    _ColimaService_ProcessList_Handler,
		},
		{
			MethodName: "KillProcess",
			Handler:    _ColimaService_KillProcess_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Start",
			Handler:       _ColimaService_Start_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Restart",
			Handler:       _ColimaService_Restart_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ModelSetup",
			Handler:       _ColimaService_ModelSetup_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ModelRun",
			Handler:       _ColimaService_ModelRun_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "VMStats",
			Handler:       _ColimaService_VMStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "colima_ui.proto",
}
