// Package proto contains the gRPC service stubs for colima-ui.
// In production, this is generated by protoc from ../proto/colima_ui.proto.
// This stub allows the daemon to compile without running protoc.
package proto

import "context"

// Service registration (stub for grpc.RegisterService)
type ColimaServiceServer interface {
	Start(*StartRequest, ColimaService_StartServer) error
	Stop(context.Context, *StopRequest) (*StatusResponse, error)
	Restart(*RestartRequest, ColimaService_RestartServer) error
	Delete(context.Context, *DeleteRequest) (*StatusResponse, error)
	Status(context.Context, *StatusRequest) (*VMStatus, error)
	Version(context.Context, *Empty) (*VersionResponse, error)
	Update(context.Context, *Empty) (*StatusResponse, error)
	Prune(context.Context, *PruneRequest) (*StatusResponse, error)
	SSHConfig(context.Context, *ProfileRequest) (*SSHConfigResponse, error)
	ListProfiles(context.Context, *Empty) (*ProfileList, error)
	CreateProfile(context.Context, *CreateProfileRequest) (*StatusResponse, error)
	DeleteProfile(context.Context, *DeleteProfileRequest) (*StatusResponse, error)
	CloneProfile(context.Context, *CloneProfileRequest) (*StatusResponse, error)
	KubernetesStart(context.Context, *ProfileRequest) (*StatusResponse, error)
	KubernetesStop(context.Context, *ProfileRequest) (*StatusResponse, error)
	KubernetesReset(context.Context, *ProfileRequest) (*StatusResponse, error)
	KubeExec(context.Context, *KubeExecRequest) (*KubeExecResponse, error)
	ProcessList(context.Context, *ProfileRequest) (*ProcessListResponse, error)
	KillProcess(context.Context, *KillProcessRequest) (*StatusResponse, error)
	VMStats(*ProfileRequest, ColimaService_VMStatsServer) error
}

type UnimplementedColimaServiceServer struct{}

func (UnimplementedColimaServiceServer) Start(*StartRequest, ColimaService_StartServer) error {
	return nil
}
func (UnimplementedColimaServiceServer) Stop(context.Context, *StopRequest) (*StatusResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) Restart(*RestartRequest, ColimaService_RestartServer) error {
	return nil
}
func (UnimplementedColimaServiceServer) Delete(context.Context, *DeleteRequest) (*StatusResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) Status(context.Context, *StatusRequest) (*VMStatus, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) Version(context.Context, *Empty) (*VersionResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) Update(context.Context, *Empty) (*StatusResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) Prune(context.Context, *PruneRequest) (*StatusResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) SSHConfig(context.Context, *ProfileRequest) (*SSHConfigResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) ListProfiles(context.Context, *Empty) (*ProfileList, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) CreateProfile(context.Context, *CreateProfileRequest) (*StatusResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) DeleteProfile(context.Context, *DeleteProfileRequest) (*StatusResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) CloneProfile(context.Context, *CloneProfileRequest) (*StatusResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) KubernetesStart(context.Context, *ProfileRequest) (*StatusResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) KubernetesStop(context.Context, *ProfileRequest) (*StatusResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) KubernetesReset(context.Context, *ProfileRequest) (*StatusResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) KubeExec(context.Context, *KubeExecRequest) (*KubeExecResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) ProcessList(context.Context, *ProfileRequest) (*ProcessListResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) KillProcess(context.Context, *KillProcessRequest) (*StatusResponse, error) {
	return nil, nil
}
func (UnimplementedColimaServiceServer) VMStats(*ProfileRequest, ColimaService_VMStatsServer) error {
	return nil
}

// Stream interfaces
type ColimaService_StartServer interface{ Send(*ProgressEvent) error }
type ColimaService_RestartServer interface{ Send(*ProgressEvent) error }
type ColimaService_VMStatsServer interface{ Send(*VMStatsEvent) error }

// Message types
type Empty struct{}
type StatusResponse struct {
	Success bool
	Message string
	Error   string
}
type ProgressEvent struct {
	Stage    string
	Message  string
	Progress float32
	Done     bool
	Error    string
}
type StartRequest struct {
	Profile string
	Config  *ColimaConfig
}
type StopRequest struct {
	Profile string
	Force   bool
}
type RestartRequest struct{ Profile string }
type DeleteRequest struct {
	Profile string
	Data    bool
	Force   bool
}
type StatusRequest struct {
	Profile  string
	Extended bool
}
type VMStatus struct {
	Running      bool
	DisplayName  string
	Driver       string
	Arch         string
	Runtime      string
	MountType    string
	IpAddress    string
	DockerSocket string
	Kubernetes   bool
	Cpu          int32
	Memory       int64
	Disk         int64
	Version      string
}
type VersionResponse struct {
	Version  string
	Revision string
}
type PruneRequest struct{ All bool }
type ProfileRequest struct{ Profile string }
type SSHConfigResponse struct {
	Config       string
	Host         string
	Port         int32
	User         string
	IdentityFile string
}
type ProfileList struct{ Profiles []*ProfileInfo }
type ProfileInfo struct {
	Name      string
	Status    string
	Arch      string
	Cpus      int32
	Memory    int64
	Disk      int64
	Runtime   string
	IpAddress string
}
type CreateProfileRequest struct {
	Name   string
	Config *ColimaConfig
}
type DeleteProfileRequest struct {
	Name  string
	Data  bool
	Force bool
}
type CloneProfileRequest struct {
	Source      string
	Destination string
}
type ColimaConfig struct {
	Cpu                  int32
	Memory               float32
	Disk                 int32
	RootDisk             int32
	Arch                 string
	VmType               string
	CpuType              string
	Rosetta              bool
	NestedVirtualization bool
	Hostname             string
	DiskImage            string
	Binfmt               bool
	PortForwarder        string
	Runtime              string
	AutoActivate         bool
	ModelRunner          string
	MountType            string
	MountInotify         bool
	ForwardAgent         bool
	SshConfig            bool
	SshPort              int32
}
type KubeExecRequest struct {
	Profile string
	Command string
}
type KubeExecResponse struct {
	Output   string
	Error    string
	ExitCode int32
}
type ProcessListResponse struct{ Processes []*ProcessInfo }
type ProcessInfo struct {
	Pid           int32
	User          string
	CpuPercent    float64
	MemoryPercent float64
	Command       string
	Container     string
}
type KillProcessRequest struct {
	Profile string
	Pid     int32
	Signal  int32
}
type VMStatsEvent struct {
	CpuPercent  float64
	MemoryUsed  int64
	MemoryTotal int64
	DiskUsed    int64
	DiskTotal   int64
	Timestamp   int64
}

// RegisterColimaServiceServer registers the service with a gRPC server.
func RegisterColimaServiceServer(s interface{ RegisterService(desc interface{}, impl interface{}) }, srv ColimaServiceServer) {
	// In production, this is generated by protoc-gen-go-grpc
	_ = s
	_ = srv
}
